<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('blogs')->insert([
            [   'naslov_blog' => '<h3><strong>Kucna nega</strong></h3>',
                'text_blog' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
                'podnaslov_blog' => '<p>Lorem ipsum dolor sit amet</p>',
                'status' => 1,
                'putanja_slika_blog' => 'kucna_nega.gif',
                'video_link' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/HngnXzHuvS8?si=6xzgi4M_oZ_FbFUA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
                'postavljeno'  => '1699099513',
                'description'  => '<p>kucna nega</p>',
                'keywords'  => '<p>kucna nega</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Higijenski tretman lica</strong></h3>',
                'text_blog' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>',
                'podnaslov_blog' => '<p>Lorem ipsum dolor sit amet</p>',
                'status' => 1,
                'putanja_slika_blog' => 'hidroderma_abrazija_aqua_peel.png',
                'video_link' => null,
                'postavljeno'  => '1638318873',
                'description'  => '<p>nesto</p>',
                'keywords'  => '<p>nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Antiage</strong></h3>',
                'text_blog' => '<p>Starenje kože počinje dosta pre nego &scaron;to mi vidimo prve bore i ostale znakove starenja na koži. Znakovi starenja kože su pokazatelji da na&scaron; organizam nije vi&scaron;e u stanju da izvr&scaron;ava sve funkcije regeneracije, kao &scaron;to je to radio pre. Prvi znak starenja kože je nedostatak hidratacije, koji počinje oko 20 &ndash;te godine, a nakon toga se pojavljuje bezživotnost kože, koju možemo primetiti u samoj boji kože lica. Treći stadijum starenja je pojava solarnih pega i početni pad tonusa kože,gubitak čvrstoće, pojava prvih mimičkih linija i nazolabijanih bora koje se vide i bez same mimike lica. Kao poslednji stadijum starenja kože imamo pojavu slojeva kože koji ne uspevaju da se obnove. Starenje kože je neizbežno a spoljni uticaji znatno uticu na starenje kože, kao &scaron;to su izlaganje suncu UVA i UVB, zracenje plavog svetla(mobilni telefoni, kompjuter...), zagadjenje, Na starenje takodje jako utiče stres, poremećaj spavanja, pu&scaron;enje. Sve navedeno je okidač slobodnim radikalima da proizvode oksidativni stres i da se dogadjaju razne degeneracije na strukturama na&scaron;e kože koji dovode do posledica starenja. Odabir preparata i aparaturnih metoda podmadjivanja odredjujemo za svakog klijenta zasebno na konsultacijama.</p>',
                'podnaslov_blog' => '<p>Starenje kože počinje dosta pre nego &scaron;to mi vidimo prve bore</p>',
                'status' => 1,
                'putanja_slika_blog' => 'antiage.gif',
                'video_link' => null,
                'postavljeno'  => '1638319119',
                'description'  => '<p>nesto</p>',
                'keywords'  => '<p>nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Tretmani či&scaron;ćenja lica</strong>...',
                'text_blog' => '<p>Osnova negovane kože, leži u redovnom praktikovanju tretmana či&scaron;čenja,koji predstavljaju deo lične higijene lica.Samo čiste pore mogu da prime aktivne kompronente i preparate kućne nege. Ovakvi tretmani podrazumevaju niz postupaka kojim se vr&scaron;i dubinsko či&scaron;ćenje kože. Protokol tretmana prilagodjava se potrebama klijenta u zavisnosti od tipa i stanja kože. Klasičan tretman lica traje sat do sat i po vremena i preporučujemo da se radi jednom u mesec dana, u zavisnosti od individualnih potreba kože.</p>',
                'podnaslov_blog' => '<p>Osnova negovane kože, leži u redovnom praktikovanju tretmana či&scaron;čenja</p>',
                'status' => 1,
                'putanja_slika_blog' => 'tretmani_ciscenja_lica.jpg',
                'video_link' => null,
                'postavljeno'  => '1638318814',
                'description'  => '<p>nesto</p>',
                'keywords'  => '<p>nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Vrste pilinga</strong></h3>',
                'text_blog' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In commodo malesuada quam eget tincidunt. Integer dolor tortor, hendrerit id maximus sed, venenatis sed sem. Etiam et vestibulum lectus. Fusce vel nunc ac purus hendrerit venenatis. Mauris a magna condimentum lectus ultrices congue vitae at libero. Vestibulum ut imperdiet odio. Maecenas nec turpis cursus, aliquet elit nec, luctus lacus. Integer volutpat lectus ut dictum fermentum. Sed placerat dui nulla, et mollis diam lacinia eu. Vivamus finibus tincidunt diam, vel pellentesque ante rutrum tincidunt. In hac habitasse platea dictumst. Nunc vel velit nec enim ullamcorper dictum.</p>',
                'podnaslov_blog' => '<p>Lorem ipsum dolor</p>',
                'status' => 1,
                'putanja_slika_blog' => 'collage.png',
                'video_link' => null,
                'postavljeno'  => '1638319081',
                'description'  => '<p>nesto</p>',
                'keywords'  => '<p>nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Nesto nesto</strong></h3>',
                'text_blog' => '<p>Nesto 44444</p>',
                'podnaslov_blog' => '<p>Nesto</p>',
                'status' => 1,
                'putanja_slika_blog' => 'radiotalasni_lifting1.png',
                'video_link' => null,
                'postavljeno'  => '1638319059',
                'description'  => '<p>nesto</p>',
                'keywords'  => '<p>nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h4><strong>Nesto nesto</strong></h4>',
                'text_blog' => '<p>Nesto nesto</p>',
                'podnaslov_blog' => '<p>Nesto&nbsp;</p>',
                'status' => 0,
                'putanja_slika_blog' => 'alex.PNG',
                'video_link' => '<iframe width="560" height="315" src="https://www.youtube.com/embed/Fpn1imb9qZg?si=mEPTgeKBGLI2yoM5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
                'postavljeno'  => '1699098410',
                'description'  => '<p>Nesto nesto</p>',
                'keywords'  => '<<p>Nesto nesto</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   'naslov_blog' => '<h3><strong>Lorem ipsum</strong></h3>',
                'text_blog' => '<h3><strong>Lorem ipsum</strong></h3>',
                'podnaslov_blog' => 'lorem Ipsum',
                'status' => 1,
                'putanja_slika_blog' => '',
                'video_link' =>null,
                'postavljeno'  => '1699098419',
                'description'  => '',
                'keywords'  => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
